[target.aarch64-unknown-linux-gnu]
openssl-sys = "0.9.76"
pre-build = ["apt-get update && apt install rustc cargo libasound2-dev libssl-dev pkg-config"]

[target.x86_64-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install --assume-yes  libasound2-dev"]

